import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainLayout from "@/layouts/MainLayout.layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Serene Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-screen  overflow-hidden relative">
          <div className="relative min-h-screen w-full z-10">
            <MainLayout>
              <main className="bg-transparent h-[92vh] overflow-x-hidden overflow-hidden">
                {children}
              </main>
            </MainLayout>
          </div>
        </div>
      </body>
    </html>
  );
}
