import FloorPlan from "@/components/NavPlans";
import { Metadata } from "next";
import React from "react";

interface IProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Serene Detail",
  description: "Generated by create next app",
};
export default function DetailLayout({ children }: IProps) {
  return (
    <div className="relative h-[92vh] overflow-x-hidden overflow-hidden">
      {children}
      <FloorPlan />
    </div>
  );
}
