import { Metadata } from "next";
import React from "react";

interface IProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Serene Detail",
  description: "Generated by create next app",
};
export default function DetailLayout({ children }: IProps) {
  return <div>{children}</div>;
}
